## Basic Configuration
baseurl = "founable.com"
languageCode = "en"

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true

## Site Settings
[params]
    author = "Jack Teoh"
    title = "Founable"
    description = " "
    authorimage = "/images/potrait.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id" 

## Social Accounts
[params.social]
    github = "jackteoh"
    instagram = ""
    xing = ""
    linkedin = "jackteoh"
    twitter = ""
    facebook = ""
    stackoverflow = ""
    email = "contact@founable.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
